name: "[Server] - TypeScript"

on:
  pull_request:
    branches: [master]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: cd apps/server && npm install

      - name: Run TypeScript checks
        run: cd apps/server && npm run type-check

      - name: Run TypeScript Coverage
        run: cd apps/server && npm run ts-coverage
